//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Print {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Print() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Print", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advance Payment Tax.
        /// </summary>
        internal static string Invoice_AdvancePaymentTax {
            get {
                return ResourceManager.GetString("Invoice_AdvancePaymentTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To be paid to the Tax agency in behalf of {0}.
        /// </summary>
        internal static string Invoice_AdvancePTComment {
            get {
                return ResourceManager.GetString("Invoice_AdvancePTComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company Number.
        /// </summary>
        internal static string Invoice_CompanyNumber {
            get {
                return ResourceManager.GetString("Invoice_CompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Invoice_Email {
            get {
                return ResourceManager.GetString("Invoice_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item.
        /// </summary>
        internal static string Invoice_Item {
            get {
                return ResourceManager.GetString("Invoice_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice number {1}# {0} #.
        /// </summary>
        internal static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank wire.
        /// </summary>
        internal static string Invoice_PaymentDetails {
            get {
                return ResourceManager.GetString("Invoice_PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment details.
        /// </summary>
        internal static string Invoice_PaymentDetailsTitle {
            get {
                return ResourceManager.GetString("Invoice_PaymentDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Invoice_Phone {
            get {
                return ResourceManager.GetString("Invoice_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Invoice_Price {
            get {
                return ResourceManager.GetString("Invoice_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qty.
        /// </summary>
        internal static string Invoice_Qty {
            get {
                return ResourceManager.GetString("Invoice_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Service.
        /// </summary>
        internal static string Invoice_Service {
            get {
                return ResourceManager.GetString("Invoice_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubTotal.
        /// </summary>
        internal static string Invoice_SubTotal {
            get {
                return ResourceManager.GetString("Invoice_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        internal static string Invoice_To {
            get {
                return ResourceManager.GetString("Invoice_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Invoice_Total {
            get {
                return ResourceManager.GetString("Invoice_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total to Pay.
        /// </summary>
        internal static string Invoice_TotalToPay {
            get {
                return ResourceManager.GetString("Invoice_TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VAT.
        /// </summary>
        internal static string Invoice_VAT {
            get {
                return ResourceManager.GetString("Invoice_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proposal.
        /// </summary>
        internal static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
    }
}
