//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Print {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Print() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Print", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Payment Tax.
        /// </summary>
        internal static string Invoice_AdvancePaymentTax {
            get {
                return ResourceManager.GetString("Invoice_AdvancePaymentTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be paid to the Tax agency in behalf of {0}.
        /// </summary>
        internal static string Invoice_AdvancePTComment {
            get {
                return ResourceManager.GetString("Invoice_AdvancePTComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Number.
        /// </summary>
        internal static string Invoice_CompanyNumber {
            get {
                return ResourceManager.GetString("Invoice_CompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Invoice_Email {
            get {
                return ResourceManager.GetString("Invoice_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Invoice_Item {
            get {
                return ResourceManager.GetString("Invoice_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number {1}# {0} #.
        /// </summary>
        internal static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank wire.
        /// </summary>
        internal static string Invoice_PaymentDetails {
            get {
                return ResourceManager.GetString("Invoice_PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment details.
        /// </summary>
        internal static string Invoice_PaymentDetailsTitle {
            get {
                return ResourceManager.GetString("Invoice_PaymentDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Invoice_Phone {
            get {
                return ResourceManager.GetString("Invoice_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Invoice_Price {
            get {
                return ResourceManager.GetString("Invoice_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Invoice_Qty {
            get {
                return ResourceManager.GetString("Invoice_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Invoice_Service {
            get {
                return ResourceManager.GetString("Invoice_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        internal static string Invoice_SubTotal {
            get {
                return ResourceManager.GetString("Invoice_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Invoice_To {
            get {
                return ResourceManager.GetString("Invoice_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Invoice_Total {
            get {
                return ResourceManager.GetString("Invoice_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to Pay.
        /// </summary>
        internal static string Invoice_TotalToPay {
            get {
                return ResourceManager.GetString("Invoice_TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string Invoice_VAT {
            get {
                return ResourceManager.GetString("Invoice_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        internal static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal Details.
        /// </summary>
        internal static string ProposalDetails {
            get {
                return ResourceManager.GetString("ProposalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Proposal_Total {
            get {
                return ResourceManager.GetString("Proposal_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT is not included.
        /// </summary>
        internal static string VAT_Not_Included {
            get {
                return ResourceManager.GetString("VAT_Not_Included", resourceCulture);
            }
        }
    }
}
